CRUD_app/urls.py
from django.urls import include, path
from .import views

app_name = 'CRUD_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.create_user, name='signup'),
    path('signin/', views.sign_in, name='signin'),
    path('signout/', views.sign_out, name='signout'),
    path('delete/<int:id>/', views.delete_user, name='deleteUser'),
    path('edit/<int:id>/', views.edit_user, name='editUser'),

]

RID_IT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CRUD_app.urls', namespace='CRUD_app')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

CRUD_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class NewUser(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='related_user')
    full_name = models.CharField(max_length=150)
    image = models.ImageField(upload_to='crud_app/', blank=True)

    def __str__(self):
        return self.full_name

    def image_url(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

CRUD_app/forms.py
from django import forms
from .models import NewUser


# class UserRegForm(forms.ModelForm):
#     class Meta:
#         model = NewUser
#         fields = ['full_name', 'email', 'password1', 'password2']
#         widgets = {
#             'name':forms.TextInput(attrs={'class':'form-control'}),
#             'email':forms.EmailInput(attrs={'class':'form-control'}),
#             'password1':forms.PasswordInput(render_value=True, attrs={'class':'form-control'}),
#             'password2':forms.PasswordInput(render_value=True, attrs={'class':'form-control'}),
#         }

class RegisterForm(forms.Form):
    full_name = forms.CharField(label='Full Name', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your Name'}))

    user_name = forms.CharField(label='Username', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your Username'}))

    email = forms.EmailField(label='Email', required=False,
                             widget=forms.EmailInput(attrs={'placeholder': 'example@email.com'}))

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={'placeholder': 'Enter Password'}))

    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(
        attrs={'placeholder': 'Confirm Password'}))

    image = forms.ImageField(label='image', required=False)


class LoginForm(forms.Form):
    user_name = forms.CharField(label='Username', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your Username'}))

    password = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Password'}))


class EditForm(forms.ModelForm):
    full_name = forms.CharField(label='Full Name', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your Name'}))

    image = forms.ImageField(label='image', required=False)

    class Meta:
        model = NewUser()
        fields = ['full_name', 'image']

CRUD_app/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from CRUD_app.models import NewUser
from CRUD_app.forms import RegisterForm, LoginForm, EditForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def home(request):
    blogers = NewUser.objects.all()
    return render(request, 'crud_app/home.html', {'all_blogers': blogers})


def edit_user(request, id):
    if request.method == 'POST':
        single_bloger = get_object_or_404(NewUser, id=id)
        frm = EditForm(request.POST, instance=single_bloger)
        if frm.is_valid():
            frm.save()
            messages.success(
                request, "Account for {0} is created Successfully".format(single_bloger))
            return redirect('CRUD_app:home')
    else:
        single_bloger = get_object_or_404(NewUser, id=id)
        frm = EditForm(instance=single_bloger)
    return render(request, 'crud_app/editprofile.html', {'single_bloger': single_bloger, 'form': frm})


def delete_user(request, id):
    obj = get_object_or_404(NewUser, id=id)
    if request.method == 'POST':
        obj.delete()
        return redirect('CRUD_app:home')
    return render(request, "crud_app/delete.html", context={'object': obj})


def create_user(request):
    if request.method == 'POST':
        fm = RegisterForm(request.POST, request.FILES)
        if fm.is_valid():
            print("form valid")
            full_name = fm.cleaned_data.get('full_name')
            image = fm.cleaned_data.get('image')
            username = fm.cleaned_data.get('user_name')
            email = fm.cleaned_data.get('email')
            password1 = fm.cleaned_data.get('password1')
            password2 = fm.cleaned_data.get('password2')

            if User.objects.filter(username=username).exists():
                messages.error(
                    request, "Customer with this  {0} username is already exists".format(username))
                return redirect('CRUD_app:signup')
            else:
                if password1 != password2:
                    messages.error(request, "Password does not match")
                    return redirect('CRUD_app:signup')

                else:
                    password_hash = make_password(password2)
                    user = User.objects.create(
                        username=username, password=password_hash, email=email)

                    new_user = NewUser()
                    new_user.user = user
                    new_user.full_name = full_name
                    new_user.image = image
                    new_user.save()

                    messages.success(
                        request, "Account for {0} is created Successfully".format(user))
                    return redirect('CRUD_app:home')

    else:
        fm = RegisterForm()
    return render(request, 'crud_app/signUpUser.html', {'form': fm})


def sign_in(request):
    if not request.user.is_authenticated:
        form = LoginForm()
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                print('valid: ')
                user_name = form.cleaned_data['user_name']
                password = form.cleaned_data['password']
                user = authenticate(username=user_name, password=password)
                if user:
                    login(request, user)
                    print("successfully login")
                    messages.success(request, "Logged in Successfully")
                    return redirect('CRUD_app:home')
                else:
                    print('not authenticate')
        return render(request, 'CRUD_app/login.html', {'form': form})
    else:
        return redirect('CRUD_app:home')


def sign_out(request):
    logout(request)
    messages.success(request, "Logged Out Successfully")
    return redirect("CRUD_app:signin")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title_block %} {{title}} {% endblock %}</title>
  
    <link rel="stylesheet" href="{% static 'crud_app/css/bootstrap.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

</head>
<body>
 
  <div class = 'container  justify-content-center mt-2'>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">

            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only"></span></a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'CRUD_app:signup' %}">SignUp</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'CRUD_app:signout' %}">LogOut</a>
              </li>
            {% else %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'CRUD_app:signin' %}">LogIn</a>
            </li>
            {% endif %}


          </ul>
        </div>
    </nav>
  </div>

  <div class = 'container mt-5'>
    <div class = 'row text-center justify-content-center mb-3'>

      {% if messages %}
          {% for message in messages %}

          <div class="alert alert-{{ message.tag }} alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          
          {% endfor %}
          
      {% endif %}
        </div>
    <div class='mt-4 d-flex justify-content-center'> 
          
      {% block content %}
      
      {% endblock content %}
    </div> 
  </div>

    <link rel="stylesheet" href="{% static 'crud_app/js/bootstrap.js' %}">
    <link rel="stylesheet" href="{% static 'crud_app/js/jquery.js' %}">
    <link rel="stylesheet" href="{% static 'crud_app/js/popper.js' %}">
</body>
</html>

templates/crud_app/delete.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %} Delete Page {% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="mb-4 col-12 ">
        <div class="shadow-sm card border-light components-section">
            <div class="text-center text-white card-header bg-info">
            <h5>Delete {{object}}</h5>
            </div>
            <div class="card-body">
                <div class="mb-4 row justify-content-center">
                    <!-- (multipart/form-data)This value is necessary if the user will upload a file through the form -->
                    <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-lg-12 col-sm-12">
                        <!-- Form -->
                        <div class="row">
                            <div class="mb-4 text-center">
                                are you sure to delete this {{object}}?
                            </div>  
                        </div>
                        <div class="mb-4 text-center">
                            <a class="btn btn-block btn-warning" href="{% url 'CRUD_app:home' %}">Back</a>
                            <button class="btn btn-block btn-danger" type="submit">Delete</button>
                            
                        </div>
                        <!-- End of Form -->

                    </div>
                </form>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/crud_app/editprofile.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %} Edit Page {% endblock %}
{% block content %}

<div class="container rounded bg-white mt-5 mb-5">
    <div class="row justify-content-center">
        <form action="" method='POST' enctype='multipart/form-data'>
            {% csrf_token %}
            <div class="col-md-5 border-right">
                <div class="p-3 py-5">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h4 class='text-center alert alert-info'>Profile Settings</h4>
                    </div>

                        <div class="row mt-2">
                            <div class="col-md-6"><label class="labels"></label>
                                {{form.full_name}}
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-md-6"><label class="labels"></label>
                                {{form.image}}
                            </div>
                        </div>

                        <div class="mt-5 text-center">
                            <a class="btn btn-block btn-warning" href="{% url 'CRUD_app:home' %}">Back</a>
                            <button type="submit" class="btn btn-primary profile-button">Save Profile</button>
                        </div>
                        
                        <div class="mt-5 text-center">
                            
                        </div>
                    

                </div>
            </div>
        </form>

    </div>
</div>


{% endblock content %}

templates/crud_app/home.html
{% extends 'base.html' %}
{% block title_block %} Home Page {% endblock %}
{% block content %}

<div class="col-sm-7">
    <h3 class='text-center alert alert-info'>All User Here</h3>
    {% if all_blogers %}
        <table class="table">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Image</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
                {% for bloger in all_blogers %}
                <tr>
                    <th scope="row">{{bloger.id}}</th>
                    <td>{{bloger.full_name}}</td>
                    <td>{{bloger.user.email}}</td>
                    <td><img class='rounded' style='width:50px; height:50px;' src='{{ bloger.image_url }}'></td>
                    {% if request.user.is_authenticated %}
                    <td>
                        <a href="{% url 'CRUD_app:editUser' id=bloger.id %}" class= 'btn btn-warning btn-sm'>Edit</a>

                        <a href="{% url 'CRUD_app:deleteUser' id=bloger.id %}" class= 'btn btn-danger btn-sm'>Delete</a>
                        
                    </td>
                    {% else %}
                    <td>
                        Please Login!
                    </td>
                    {% endif %}
                    
                </tr>
                {% endfor %}
            
            </tbody>
        </table>
    {% endif %}
        
</div>

{% endblock content %}


templates/crud_app/login.html
{% extends 'base.html' %}
#{% load crispy_forms_tags %}
{% load static %}
{% block title_block %} Login Page {% endblock %}
{% block content %}


    <div class="container-fluid vh-100" >
        <div class="">
            <div class="rounded d-flex justify-content-center">
                <div class="col-md-6 col-sm-12 shadow-lg p-5 bg-light">
                    <div class="text-center">
                        <h3 class="text-primary">Sign In</h3>
                    </div>
                    <form action="" method='POST'>
                        {% csrf_token %}
                        <div class="p-4">
                            <div class="input-group mb-3">
                                <span class="input-group-text bg-primary"><i
                                        class="bi bi-person-plus-fill text-white"></i></span>
                                        {{form.user_name}}
                            </div>
                            <div class="input-group mb-3">
                                <span class="input-group-text bg-primary"><i
                                        class="bi bi-key-fill text-white"></i></span>
                                        {{form.password}}
                            </div>
                            
                            <div class="text-end">
                                <span class=" text-primary">Forgot your password?</span>
                            </div>
                            <div class="text-center">
                                <button class="btn btn-primary  mt-2" type="submit">
                                Login
                            </button>
                            </div>
                            
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



{% endblock content %}


templates/crud_app/signUpUser.html
{% extends 'base.html' %}
#{% load crispy_forms_tags %}
{% block title_block %} Signup Page {% endblock %}
{% block content %}


<form action="" method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    <div class="mb-3">
        {{form.full_name}}
    </div>
    <div class="mb-3">
        {{form.user_name}}
    </div>
    <div class="mb-3">
        {{form.image}}
    </div>
    <div class="mb-3">
        {{form.email}}
    </div>
    <div class="mb-3">
        {{form.password1}}
    </div>

    <div class="mb-3">
        {{form.password2}}
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>


{% endblock content %}
